addedOn: 2022-12-10
name: Netlify
logo: netlify.svg
website: https://www.netlify.com/
summary: A cloud platform for building, deploying, and managing modern web applications. It offers continuous deployment, serverless functions, and a global edge network.
